Lint/AssignmentInCondition:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NilComparison:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 85
